In [180]:
import numpy as np

poids = [323, 982, 158, 420, 879, 765, 629, 786, 30, 268, 910, 289]
values = [20, 31, 17, 67, 92, 70, 82, 41, 94, 2, 34, 12]
max_wight = 3000


In [181]:
def bin_to_dec(_bin):   
    return int(_bin, 2)

In [182]:
def fitness(chromosome):
    fitt = 0
    total_wight = 0
    for i in range(0,len(chromosome)-1):
        fitt = values[i]*chromosome[i]+fitt
        total_wight = poids[i]*chromosome[i]+total_wight
    
    if(total_wight > max_wight):
        chromosome[-1] = 0
    else:
        chromosome[-1] = fitt
    
    return chromosome

In [183]:
def selection(_Pop):
    winners = []
    for i in range(2):
        index1 = np.random.randint(len(_Pop))
        index2 = np.random.randint(len(_Pop))
        fitness1 = fitness(_Pop[index1])
        fitness2 = fitness(_Pop[index2])
        if fitness1[-1] > fitness2[-1]:
            winners.append(fitness1)
        else:
            winners.append(fitness2)
    return np.array(winners)

In [184]:
def crossover(_Pop, prob_cr):
    if np.random.rand() > prob_cr:
        crossover_result = []
        origine1, origine2 = _Pop[0], _Pop[1]
        crossover_result.append(fitness(origine1))
        crossover_result.append(fitness(origine2))
        
        point_cross = np.random.randint(0, len(origine1))
        chromosom1 = np.concatenate((origine1[:point_cross],origine2[point_cross:]))
        chromosom2 = np.concatenate((origine2[:point_cross],origine1[point_cross:]))
        crossover_result.append(fitness(chromosom1))
        crossover_result.append(fitness(chromosom2))
        return np.array(crossover_result)
    else: 
        return _Pop

In [185]:
def mutation(_Pop, prob_mutation):
    if np.random.rand() > prob_mutation: 
        random_chrom = np.random.randint(0, len(_Pop))
        new_chrom = _Pop[random_chrom]
        random_index = np.random.randint(0, len(_Pop[0])-1)
        new_chrom[random_index]= 1 - _Pop[random_chrom][random_index]
        return np.vstack([_Pop, fitness(new_chrom)])
    else:
        return _Pop


In [186]:
def genetic_algorithm():
    N_pop = 25
    n_bits = 13
    
    initial_Pop = np.random.randint(2, size=(N_pop, n_bits))
    ini = np.empty((0,n_bits),dtype=int)
    for i in initial_Pop:
        ini = np.vstack([ini, fitness(i)])
   
    print("First Population : ")
    print(ini)

    evalouted_pop = initial_Pop
    
    prob_cr = 0.5
    prob_mutation = 0.07

    max_gen = 100
    
    for i in range(0,max_gen):
        temp_Pop = np.empty((0,n_bits),dtype=int)

        while(len(temp_Pop) <= N_pop):
            _selection = selection(evalouted_pop)
            _crossover = crossover(_selection,prob_cr)
            _mutation = mutation(_crossover,prob_mutation)
            temp_Pop = np.vstack([temp_Pop, _mutation])
        evalouted_pop = temp_Pop
    
    return evalouted_pop
        

In [226]:
Soultion = genetic_algorithm()

print("")
print("the last generation is ")


last_col = Soultion[:,-1]
sorted_indices = np.argsort(last_col)[::-1]

sorted_solutions = Soultion[sorted_indices]
print(sorted_solutions)

best_found = sorted_solutions[0]
fitt = 0
total_wight = 0
items = 0
for i in range(0,len(best_found)-1):
    items = items + best_found[i]
    fitt = values[i]*best_found[i]+fitt
    total_wight = poids[i]*best_found[i]+total_wight
    
        
best_found[-1] = fitt
print("max items to pick = ",items)
print("")
print("total wight = ",total_wight)
print("")
print("fittness  = ",fitt)

First Population : 
[[  1   0   0   1   1   1   1   0   0   1   0   1   0]
 [  0   0   1   1   0   0   1   1   0   0   1   1   0]
 [  1   1   0   0   1   0   0   0   0   0   0   1 155]
 [  0   0   1   1   1   0   1   0   1   0   0   1 364]
 [  0   1   1   1   1   0   0   1   1   0   0   0   0]
 [  0   1   1   0   0   1   1   1   0   0   1   1   0]
 [  0   1   1   0   0   1   1   1   1   0   0   1   0]
 [  0   1   1   0   1   0   1   1   1   0   1   0   0]
 [  0   0   0   1   1   1   1   1   0   0   1   1   0]
 [  0   1   1   0   1   1   1   0   1   0   1   0   0]
 [  0   0   1   1   0   1   1   1   0   1   0   1   0]
 [  0   1   1   1   0   0   0   1   1   0   0   0 250]
 [  0   0   1   0   0   1   1   1   0   0   0   0 210]
 [  0   1   1   0   1   1   0   1   0   0   1   0   0]
 [  0   1   0   1   0   0   1   0   0   1   0   1 194]
 [  0   1   0   0   0   1   1   0   1   1   0   0 279]
 [  0   0   0   1   0   1   0   1   1   1   1   1   0]
 [  0   0   0   1   1   0   0   1   0   0   1

In [189]:


# def fitness(chromosome):
#     fitt = 0
#     total_wight = 0
#     for i in range(0,len(chromosome)-1):
#         if (total_wight + poids[i]*chromosome[i]) < max_wight:
#             fitt = values[i]*chromosome[i]+fitt
#             total_wight = poids[i]*chromosome[i]+total_wight
#     chromosome[-1] = fitt
#     return chromosome