In [170]:
import numpy as np

In [171]:
def bin_to_dec(_bin):   
    return int(_bin, 2)

In [172]:
def fitness(chromosome):
    joined_bits = ''.join(map(str, chromosome[:5]))
    x = bin_to_dec(joined_bits)
    chromosome[-1]=31*x - x**2
    return chromosome

In [173]:
def selection(_Pop):
    winners = []
    for i in range(2):
        index1 = np.random.randint(len(_Pop))
        index2 = np.random.randint(len(_Pop))
        fitness1 = fitness(_Pop[index1])
        fitness2 = fitness(_Pop[index2])
        if fitness1[-1] > fitness2[-1]:
            winners.append(fitness1)
        else:
            winners.append(fitness2)
    return np.array(winners)

In [247]:
def crossover(_Pop, prob_cr):
    if np.random.rand() > prob_cr:
        crossover_result = []
        origine1, origine2 = _Pop[0], _Pop[1]
        crossover_result.append(fitness(origine1))
        crossover_result.append(fitness(origine2))
        
        point_cross = np.random.randint(0, len(origine1))
        chromosom1 = np.concatenate((origine1[:point_cross],origine2[point_cross:]))
        chromosom2 = np.concatenate((origine2[:point_cross],origine1[point_cross:]))
        crossover_result.append(fitness(chromosom1))
        crossover_result.append(fitness(chromosom2))
        return np.array(crossover_result)
    else: 
        return _Pop

In [279]:
def mutation(_Pop, prob_mutation):
    if np.random.rand() > prob_mutation: 
        random_chrom = np.random.randint(0, len(_Pop))
        new_chrom = _Pop[random_chrom]
        random_index = np.random.randint(0, len(_Pop[0])-1)
        new_chrom[random_index]= 1 - _Pop[random_chrom][random_index]
        return np.vstack([_Pop, fitness(new_chrom)])
    else:
        return _Pop


In [459]:
def genetic_algorithm():
    N_pop = 25
    n_bits = 6
    
    initial_Pop = np.random.randint(2, size=(N_pop, n_bits))
    
    ini = np.empty((0,n_bits),dtype=int)
    for i in initial_Pop:
        ini = np.vstack([ini, fitness(i)])
    print(initial_Pop)

    evalouted_pop = initial_Pop
    
    prob_cr = 0.5
    prob_mutation = 0.07

    max_gen = 100
    
    for i in range(0,max_gen):
        temp_Pop = np.empty((0,n_bits),dtype=int)

        while(len(temp_Pop) <= N_pop):
            _selection = selection(evalouted_pop)
            _crossover = crossover(_selection,prob_cr)
            _mutation = mutation(_crossover,prob_mutation)
            temp_Pop = np.vstack([temp_Pop, _mutation])
        evalouted_pop = temp_Pop
    
    return evalouted_pop
        

In [470]:
Soultion = genetic_algorithm()

print("the last generation is ")
print("")

last_col = Soultion[:,-1]
sorted_indices = np.argsort(last_col)[::-1]

sorted_matrix = Soultion[sorted_indices]
sorted_matrix

[[  1   1   1   1   1   0]
 [  0   1   1   1   1 240]
 [  0   0   0   0   1  30]
 [  0   0   0   1   1  84]
 [  1   0   1   1   0 198]
 [  1   1   0   0   1 150]
 [  0   0   0   1   0  58]
 [  0   0   1   0   0 108]
 [  0   1   0   0   1 198]
 [  0   0   1   0   0 108]
 [  0   0   0   0   0   0]
 [  1   1   1   1   0  30]
 [  1   1   0   1   0 130]
 [  1   0   0   1   0 234]
 [  1   1   0   0   0 168]
 [  1   0   1   1   0 198]
 [  0   1   1   1   1 240]
 [  0   0   0   0   0   0]
 [  1   0   1   0   0 220]
 [  1   0   1   1   1 184]
 [  0   1   1   1   0 238]
 [  1   0   1   1   1 184]
 [  1   0   1   1   0 198]
 [  0   1   1   1   1 240]
 [  0   1   0   0   1 198]]
the last generation is 



array([[  0,   1,   1,   1,   1, 240],
       [  0,   1,   1,   1,   1, 240],
       [  0,   1,   1,   1,   1, 240],
       [  0,   1,   1,   1,   1, 240],
       [  0,   1,   1,   1,   1, 240],
       [  0,   1,   1,   1,   1, 240],
       [  0,   1,   1,   1,   1, 240],
       [  0,   1,   1,   1,   1, 240],
       [  0,   1,   1,   1,   1, 240],
       [  0,   1,   1,   1,   1, 240],
       [  0,   1,   1,   1,   1, 240],
       [  0,   1,   1,   1,   1, 240],
       [  0,   1,   1,   1,   1, 240],
       [  0,   1,   1,   1,   1, 240],
       [  0,   1,   1,   1,   0, 238],
       [  0,   1,   1,   1,   0, 238],
       [  0,   1,   1,   1,   0, 238],
       [  0,   1,   1,   1,   0, 238],
       [  0,   1,   1,   0,   1, 234],
       [  0,   1,   1,   0,   1, 234],
       [  0,   1,   0,   1,   1, 220],
       [  0,   0,   1,   1,   1, 168],
       [  0,   0,   1,   1,   1, 168],
       [  0,   0,   1,   1,   1, 168],
       [  0,   0,   1,   1,   1, 168],
       [  1,   1,   0,   